# Generated by Django 4.2.30 on 2026-05-22 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('university', 'University'), ('market', 'Market'), ('office', 'Office'), ('hospital', 'Hospital'), ('industrial', 'Industrial')], default='restaurant', max_length=20)),
                ('region', models.CharField(choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pemba_north', 'Pemba North'), ('pemba_south', 'Pemba South'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('zanzibar_north', 'Zanzibar North'), ('zanzibar_south', 'Zanzibar South'), ('zanzibar_west', 'Zanzibar West')], default='dar_es_salaam', max_length=50)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Daily meal capacity')),
                ('payout_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'Halopesa'), ('tigopesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer')], help_text='Method for receiving payouts', max_length=20, null=True)),
                ('payout_account_number', models.CharField(blank=True, help_text='Phone number or bank account number for payouts', max_length=50, null=True)),
                ('payout_account_name', models.CharField(blank=True, help_text='Name on the payout account', max_length=100, null=True)),
                ('payout_bank_name', models.CharField(blank=True, help_text='Bank name if using bank transfer', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurants',
                'ordering': ['name'],
            },
        ),
    ]
