# Generated by Django 4.2.29 on 2026-04-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payout_account_name',
            field=models.CharField(blank=True, help_text='Name on the payout account', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payout_account_number',
            field=models.CharField(blank=True, help_text='Phone number or bank account number for payouts', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payout_bank_name',
            field=models.CharField(blank=True, help_text='Bank name if using bank transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'Halopesa'), ('tigopesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer')], help_text='Method for receiving payouts', max_length=20, null=True),
        ),
    ]
