# Generated by Django 4.2.30 on 2026-05-22 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dietary_type', models.CharField(choices=[('ulcer', 'Ulcer Diet'), ('diabetic', 'Diabetic Diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('gluten_free', 'Gluten Free'), ('low_sodium', 'Low Sodium'), ('renal', 'Renal Diet'), ('heart_healthy', 'Heart Healthy'), ('pregnancy', 'Pregnancy Diet'), ('other', 'Other Special Diet')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('foods_to_avoid', models.TextField(blank=True, help_text='List of foods to avoid (comma separated)', null=True)),
                ('recommended_foods', models.TextField(blank=True, help_text='List of recommended foods (comma separated)', null=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost per month for this dietary plan', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dietary_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PendingPlanChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal')], default='upgrade', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when the new plan takes effect (usually end of current plan)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_plan_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('student', 'Student Plan'), ('normal', 'Normal Plan'), ('premium', 'Premium Plan'), ('special', 'Special Plan')], default='normal', help_text='Plan tier determines features and target audience', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semester', 'Per Semester')], default='monthly', help_text='How often the user is billed', max_length=20)),
                ('is_student_only', models.BooleanField(default=False, help_text='If true, only verified students can subscribe')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan')),
                ('duration_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('semester', 'Semester')], max_length=20)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meals_per_day', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remaining_meals', models.IntegerField()),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dietary_plan', models.ForeignKey(blank=True, help_text='Special dietary requirements for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.dietaryplan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
