# Generated by Django 4.2.30 on 2026-05-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingplanchange',
            name='current_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='pendingplanchange',
            name='new_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_upgrades', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='pendingplanchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_plan_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
