# Generated by Django 4.2.29 on 2026-04-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_dietary_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('semester', 'Per Semester')], default='monthly', help_text='How often the user is billed', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features included in this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_student_only',
            field=models.BooleanField(default=False, help_text='If true, only verified students can subscribe'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('student', 'Student Plan'), ('normal', 'Normal Plan'), ('premium', 'Premium Plan'), ('special', 'Special Plan')], default='normal', help_text='Plan tier determines features and target audience', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingPlanChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal')], default='upgrade', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when the new plan takes effect (usually end of current plan)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='subscriptions.subscription')),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_upgrades', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_plan_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_plan_changes',
                'ordering': ['-created_at'],
            },
        ),
    ]
