# Generated by Django 4.2.30 on 2026-05-22 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount going to platform', max_digits=10)),
                ('restaurant_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount going to restaurant after platform fee', max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'Halopesa'), ('mix_by_yas', 'Mix by Yas'), ('tigopesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer'), ('selcom', 'Selcom')], max_length=20)),
                ('payer_phone', models.CharField(blank=True, help_text='Phone number used for mobile money payment', max_length=20, null=True)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant_payout_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of payout to restaurant', max_length=20)),
                ('restaurant_payout_reference', models.CharField(blank=True, help_text='Reference for payout to restaurant', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Restaurant receiving this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
