# Generated by Django 4.2.29 on 2026-04-01 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_payout_account_name_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_phone',
            field=models.CharField(blank=True, help_text='Phone number used for mobile money payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount going to platform', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage (e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant receiving this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='restaurant_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount going to restaurant after platform fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='restaurant_payout_reference',
            field=models.CharField(blank=True, help_text='Reference for payout to restaurant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='restaurant_payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of payout to restaurant', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'Halopesa'), ('mix_by_yas', 'Mix by Yas'), ('tigopesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer'), ('selcom', 'Selcom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
